### PR TITLE
minor: Update API version

### PR DESCRIPTION
**Pull request by ortix**
There is a bug in `v0.119.5` where the API will crash if there is no internet connection. The API tries to fetch the contracts from github and fails. The exception is not caught and crashed the application. The latest version, has this fix

### CODE REVIEW

**Comment by dfunckt** [comment]
The updated API will fix the crash but I think not much else will work without the ability to fetch device-types -- do you run an air-gapped open-balena instance @ortix?

Happy to approve and merge but before I can do so, could you please amend your commit message to `minor: Update API version`? That will satisfy the VersionBot/generate-version check, which is our automated versioning and changelog generator -- it'll bump the open-balena version from v3.2.2 to v3.3.0, amend the CHANGELOG and make a tag when this PR is merged.

**Comment by dfunckt** [comment]
@balena-ci retest

**Comment by ortix** [comment]
Yes I am running air-gapped. At least, I am trying to and this is the first step. Anything specific I have to do to get it to work properly?

**Comment by dfunckt** [comment]
I think the absolute minimum is to get device-type information once into the database and the simplest way is to let the API itself do that. It doesn't strictly require an always-on connection -- just once in a while should be alright.

Do note however that we're not testing air-gapped deployments at the moment and you may hit roadblocks. Feel free to reach out however for help.

Regarding versioning, I meant amending your *commit* message and force-pushing, unfortunately changing the PR title isn't picked up by the CI.

**Comment by ortix** [comment]
@dfunckt I figured that it wouldn't work by just changing the title. Thanks for the heads up.

Regarding air-gapped: I went through the source and it appears that I can also set up a private repo and use ENV variables to direct balena to use that one, instead of the one on github. Am I correct?

Due to security concerns, we would prefer not to access the internet.

**Comment by dfunckt** [comment]
@balena-ci rebase

**Comment by dfunckt** [comment]
Yes @ortix, I'd expect this to work 👍 

Thanks for addressing the commit message. I tried to rebase the PR which produced a merge commit of master on your branch -- this isn't strictly an issue but we generally prefer a linear history on master so if it's not too much trouble for you I'd appreciate it if you could do a fast-forward/rebase of your branch on latest master to get rid of it. I'll merge immediately afterwards. Sorry about that, but seems there's stuff we should do to make external contributions easier.

**Comment by thgreasi** [comment]
Resolves #121

**Comment by bartversluijs** [comment]
I think this PR is stuck at the commit message and thus the Balena CI bot can't approve it.
It's missing the following text at the end of the commit if I'm right:
```
Change-type: minor
```

If @ortix can fix this, that'd be awesome. If not, I'm happy to create a similar PR.

**Comment by ortix** [comment]
I tried but I couldn’t get it to work. I guess my git knowledge is not that good. If @bartversluijs could do it that would be great

**Comment by thgreasi** [comment]
@bartversluijs @ortix we have actually recently added support for the `major/minor/patch: `  prefix in the commit title, so this is only pending a rebase and an approval from a team member. If you can do the rebase over master, that would be great.

**Comment by pdcastro** [comment]
This PR may be superseded by #123

**Pull request closed without merging**
