### PR TITLE
Dependency upgrades 20230421

### PR DESCRIPTION
**Pull request by bartversluijs**
I've updated the following dependencies:
- Updated open-balena-db to 5.2.1 (minor change)
- Updated open-balena-registry to 2.37.2 (minor change)
- Updated open-balena-s3 to 2.25.2 (minor change)
- Updated open-balena-vpn to 11.26.0 (minor change)
- Updated open-balena-api to 11.8.3 (minor change / environment variable changes)

---

I've tested these versions by creating a new openBalena instance, which used v3.8.2 first and upgraded it to these dependencies. All seemed to work well.

What I've tested:
- Provisioning with fleet
- Downloading release from fleet
- Update release from fleet
- VPN Tunnel -> SSH
- Creating a fleet

I've tested it on the following images:
- BalenaOS 2.83.18+rev5 for QEMU 64-bit
- BalenaOS 2.65.0 for Raspberry Pi 4 (64-bit)
- BalenaOS 2.99.27 for Raspberry Pi 4 (64-bit)
- BalenaOS 2.113.18 for Raspberry Pi 4 (64-bit)
- BalenaOS 2.114.18 for Raspberry Pi 4 (64-bit)

### CODE REVIEW

**Comment by babourn** [comment]
bumping here, @balena are you guys ever going to merge this? or update any of the broken dependencies?

**Comment by shawaj** [comment]
Any news on this @thgreasi ?

**Comment by ab77** [comment]
@bartversluijs Hello, (and a very late thank you for you contribution), we've updated the build/deploy scaffold for openBalena today, which is a major refactor of the codebase, including a single Docker composition under [Renovate](https://github.com/balena-io/open-balena/pull/194) management + e2e tests to validate basic functionality automatically on each PR. This means that manual version bumps such as this, should (hopefully) no longer be necessary.

Please feel free to reopen if you feel that we've missed anything.

**Comment by shawaj** [comment]
Great work @ab77 

We will test it and report back

**Pull request closed without merging**
