### PR TITLE
Updated open-balena-s3 to 2.13.10

### PR DESCRIPTION
**Pull request by bartversluijs**
I've updated the following dependencies:
- Updated open-balena-s3 to 2.13.10 (patch)

---

In short, the S3 container pre-v2.13.9 downloads the latest release of Minio. Something changed in the latest release of Minio which breaks the container. Since v2.13.9, the Minio release is pinned to RELEASE.2022-05-04T07-45-27Z, which fixes it.

[Reference](https://forums.balena.io/t/getting-started-cannot-push-images-to-registry/360042/8)

### CODE REVIEW

**Review by dfunckt — APPROVED** [review]
Thank you @bartversluijs!

**Comment by dfunckt** [comment]
@balena-ci allow

**Comment by dfunckt** [comment]
I had to cherry-pick your commit and PR it separately in #159 which is now merged. Closing this one. Thanks again!

**Comment by bartversluijs** [comment]
@dfunckt thanks! Is there a preferred way to make changes to the repository for outsiders? Because this'll require more manual work from you and I want it to make it as smooth as possible.

**Comment by dfunckt** [comment]
That's alright, not really a problem and it's only temporary anyway as we'll have a way to kickstart the CI manually. I actually thought we were there already hence my (now deleted) comment to `balena-ci allow` this PR.

**Pull request closed without merging**
