### PR TITLE
Dependency upgrades

### PR DESCRIPTION
**Pull request by bartversluijs**
I've updated the following dependencies:
- Updated open-balena-api to 0.192.4 (minor change / environment variable changes)
- Updated open-balena-vpn to 9.27.0 (minor change / environment variable changes)
- Updated open-balena-registry to 2.24.2 (minor change / environment variable changes)
- Updated open-balena-s3 to 2.13.3 (minor change)
- Updated open-balena-db to 5.1.0 (minor change)

---

I've tested the changes by creating a new instance of open-balena.
The following OS's have been tested with Balena CLI 13.1.13:
- BalenaOS v2.65.0+rev1, supervisor 12.2.11 (development & production image)
- BalenaOS v2.80.5+rev1, supervisor 12.8.7 (development & production image)
- BalenaOS v2.88.5+rev1, supervisor 12.11.0 (development & production image / `"developmentMode": true`)

What I've tested with these BalenaOS versions:
- Provisioning with fleet
- Downloading release from fleet
- Update release from fleet
- VPN tunnel -> SSH
- Local mode

### CODE REVIEW

**Comment by dfunckt** [comment]
@bartversluijs open-balena-db can [automatically migrate](https://github.com/balena-io/open-balena-db/blob/master/balena-entrypoint.sh) the database between major versions -- did it not work for you?

**Comment by bartversluijs** [comment]
@dfunckt I saw the code, but it didn't work afaik. Do I need to initiate it manually?

I'll try it asap after your feedback if I missed something.

**Comment by dfunckt** [comment]
I think it doesn't actually work @bartversluijs. There's [this line](https://github.com/balena-io/open-balena-db/commit/59717dc58991418bb81a87bd1bbf08e60ebbfc68#diff-85aa5e08b310110f59756d9829fad7a07dc2328d6bf685e7f601836e173aea36R55] which checks for the old Postgres version to migrate from at the wrong place. It should instead look into `$PGDATA/$OLD_PG_VERSION` but getting `$OLD_PG_VERSION` is tricky. One way to figure out the correct directory might be for getting the top result from a list of directories in `$PGDATA` sorted by date created or modified. Feels a bit hacky but it's likely the only way.

**Comment by bartversluijs** [comment]
Awesome that you've invested your time to make this work! Thanks for that!

I'm planning to test this tomorrow and will let you know how it goes. If this fixes the problem, I'll edit my commit to a `minor` change, which would be better than a major bump imo!

**Comment by bartversluijs** [comment]
I've rebased the branch because of PR #139

**Comment by bartversluijs** [comment]
I've updated this PR because of https://github.com/balena-io/open-balena-db/pull/29, which will automatically upgrade the PostgreSQL database to version 13.

Because of this, I've changed the 'major' change type to 'minor' for the database container 🙂

**Comment by bartversluijs** [comment]
@dfunckt if you have time, can you take a look at this PR?
It'll update the dependencies massively and take advantage of the latest features.

**Review by dfunckt — APPROVED** [review]
Fantastic, thank you so much @bartversluijs!

**Pull request merged**
