### PR TITLE
SECURITY: Close port 3128

### PR DESCRIPTION
**Pull request by dfunckt**
Port 3128, which was used for tunneling into devices, was plain TCP and has now been closed. Tunnelling is now via `tunnel.mydomain.com:443` (see #101). balena-cli versions before v12.38.5 are now incompatible and using the tunnel command will throw an error.

Refs: #101
Change-type: patch

### CODE REVIEW

**Comment by dfunckt** [comment]
@balena-ci I self-certify!

**Comment by bartversluijs** [comment]
Hi,

I'm busy with understanding this change for my kubernetes fork, which I'm using in production at the moment. So I'd like to understand most changes made to new open-balena versions, thanks to [this post](https://github.com/balena-io/open-balena/pull/101#issuecomment-766941128).

Changing port 3128 to 443 using TLS is undoubtedly better for security, so +1 for that!
However, closing port 3128 completely will break some endpoint if I'm right. Because using the HTTP PROXY for communicating with a device's supervisor (e.g. reboot a device) uses port 3128 of a VPN container, right?

And I'm using the HTTP PROXY for custom endpoints, so our server API can communicate with a device directly, but it also uses the `vpn.<domain>:3128` HTTP PROXY. 

Does this PR mean that those functions will not work anymore? Or am I missing something? I've checked the latest [balena-io/open-balena-api](https://github.com/balena-io/open-balena-api), but that still uses the `<vpn-ip>:3128` for the HTTP PROXY communication.

Thanks in advance!

**Comment by pdcastro** [comment]
@bartversluijs, I haven't tested myself and my knowledge is limited, but could this be a matter of internal vs external access to port 3128? I understand that sockets are still listening and reachable on port 3128 "locally" in the "default network" listed in the `services.yml` file modified by this pull request, but the port is no longer mapped to the host OS and therefore not reachable ("closed") for external access "from the internet".

> Because using the HTTP PROXY for communicating with a device's supervisor (e.g. reboot a device) uses port 3128 of a VPN container, right?

If it does, I assume (but I am not 100% sure) it would be over / within the openVPN link. Here's a test you can run on a device running balenaOS. I ran the following test on a device connected to `balena-cloud.com`, not openBalena, and running a development image rather than production, but I assume it would behave similarly for openBalena and production, and in any case your results should shed some light on it:

```
$ ssh -p 22222 root@192.168.1.46
root@9a56d9b:~#
root@9a56d9b:~# netstat -ant | grep ESTABLISHED
tcp        0      0 192.168.1.46:63886      3.227.28.93:443         ESTABLISHED
tcp        0      0 ::ffff:192.168.1.46:22222 ::ffff:192.168.1.211:56619 ESTABLISHED

root@9a56d9b:~# nslookup vpn.balena-cloud.com
...
Address 3: 3.227.28.93 ec2-3-227-28-93.compute-1.amazonaws.com
```

So we see above that the device's openVPN link connects to `3.227.28.93:443` which is `vpn.balena-cloud.com:443`, not `vpn.balena-cloud.com:3128`, and this is sufficient for the balenaCloud dashboard to reach the device's supervisor to e.g. remotely reboot a device. Do you see 443 or 3128 when you attempt something similar?

> And I'm using the HTTP PROXY for custom endpoints, so our server API can communicate with a device directly, but it also uses the vpn.<domain>:3128 HTTP PROXY.

It depends on exactly what you mean, but for example the CLI's `balena ssh` command still uses the `host` and `enter` proxy commands even though port 3128 is closed, at least with balenaCloud, for example:
https://github.com/balena-io/balena-cli/blob/v12.44.1/lib/commands/ssh.ts#L225-L228

> I've checked the latest balena-io/open-balena-api, but that still uses the `<vpn-ip>:3128` for the HTTP PROXY communication.

Those may be internal URLs that resolve within the local default network, e.g.:
> https://github.com/balena-io/open-balena-api/blob/v0.133.6/src/features/device-proxy/device-proxy.ts#L268
> `proxy: `http://resin_api:${API_VPN_SERVICE_API_KEY}@${vpnIp}:${VPN_CONNECT_PROXY_PORT}`,`

Again, I haven't tested it and I could be wrong about some/all that I wrote above, but perhaps you could now try and verify or disprove my understanding, :-) which is hopefully a useful direction to follow.

**Comment by pdcastro** [comment]
> [...] but the port is no longer mapped to the host OS and therefore not reachable ("closed") for external access "from the internet".

And of course I mean external access from the internet ***directly*** to port 3128, not ***indirectly*** through the openVPN virtual link.

**Pull request merged**
