### PR TITLE
minor: Update API, registry and VPN services

### PR DESCRIPTION
**Pull request by bartversluijs**
Since there were some issues with API v0.119.5, I've tried to upgrade the [openBalena API](https://github.com/balena-io/open-balena-api) version to the highest working version, which is v0.139.0 at the moment.

And since we're upgrading, I've also tested other services for an upgrade.
The database and S3 service required some manual work, so didn't add them to the upgrade.

---

Could not upgrade the openBalena API further than v0.139.0, because of [an issue](https://github.com/balena-io/open-balena-api/issues/698)

### CODE REVIEW

**Comment by pdcastro** [comment]
> I've tried to upgrade the openBalena API version to the highest working version, which is v0.139.0 at the moment.

Thanks for this PR @bartversluijs 👍 
I see you've created issue balena-io/open-balena-api/issues/698, reporting transaction errors when updating to API v0.139.1 or later. I just wanted to check whether you ran `compose down` and `compose build` when testing the new versions, as documented in the Getting Started guide:

> https://www.balena.io/open/docs/getting-started/
> When updating openBalena to a new version, the steps are:
> $ ./scripts/compose down
> $ git pull
> $ ./scripts/compose build
> $ ./scripts/compose up -d

**Comment by bartversluijs** [comment]
Hi @pdcastro,

No problem!
About the issue, I'm using my Kubernetes Helm Chart, which starts a new container with the new version (v0.143.0 in this case) and then kills the other container. So I didn't run the `compose` commands.

But it's better to first shit down the API and then start the new one instead of a rolling update? 
I can try that by changing the strategy in Kubernetes.

**Comment by pdcastro** [comment]
> I'm using my Kubernetes Helm Chart [...]

I see. I don't know much about it but I'd just mention that some services require locally rebuilding an image when the GitHub source repo is updated, which would be achieved by the `./scripts/compose build` command, so you might want to check that Kubernetes Helm Chart is also taking care of that. Having said that, as far as I am aware, only the `haproxy` and `cert-provider` services build images locally:
https://github.com/balena-io/open-balena/blob/v3.3.2/compose/services.yml#L146
https://github.com/balena-io/open-balena/blob/v3.3.2/compose/services.yml#L182

... so `./scripts/compose build` would not make any difference to the services updated/mentioned in this PR (api, registry, vpn, database, s3).

> which starts a new container with the new version (v0.143.0 in this case) and then kills the other container
> But it's better to first shut down the API and then start the new one instead of a rolling update?

Do you mean that there would be a period of time (however brief) when two API containers would be running side by side, with different versions of the API? If so, this sounds like a recipe for trouble, :-) especially in relation do database schema migrations. Talking of which, I don't know / don't remember how database migration works in openBalena upgrades. Perhaps @dfunckt or @thgreasi or @Page- would be able to chime in, and maybe also comment on the findings of issue balena-io/open-balena-api/issues/698.

My original concern was just to be sure that the containers were recreated, so as to discard any data stored in the containers' local/internal filesystem. I think the `./scripts/compose down` command would do this to all containers, not just the ones for which a new version was pulled, although I don't know that this is strictly necessary.

**Comment by bartversluijs** [comment]
> Having said that, as far as I am aware, only the haproxy and cert-provider services build images locally:

In the Kubernetes Helm Chart, these are replaced by an HAProxy Ingress and a cert-manager of choice which are updated dynamically. But as you said, this probably doesn't make a difference in this case.

> Do you mean that there would be a period of time (however brief) when two API containers would be running side by side, with different versions of the API?

That's probably the case, but the process should be killed while the other one is starting.  If someone can confirm that this should never happen, even if it's a rolling update, I can change the Kubernetes Helm Chart so it'll stop first and then create the new one with the `Recreate` strategy.

> My original concern was just to be sure that the containers were recreated, so as to discard any data stored in the containers' local/internal filesystem. I think the ./scripts/compose down command would do this to all containers, not just the ones for which a new version was pulled, although I don't know that this is strictly necessary.

I'm sure that the old containers and thus their internal filesystem shut down before starting the new one, because they really are other containers starting.

---

But I think we're now talking more about [balena-io/open-balena-api/issues/698](https://github.com/balena-io/open-balena-api/issues/698) than this PR. Don't get me wrong, I'd like to update this PR to API version 0.143.0 once it's fixed instead of merging now and then creating another PR once it's fixed 🙂

**Review by pdcastro — APPROVED** [review]

**Comment by pdcastro** [comment]
@bartversluijs, I've approved this PR trusting your testing. :-) Let us know sooner than later if you come across any issues that require further changes. Thank you for helping us improve openBalena! 🙏

**Pull request merged**
