### PR TITLE
Restart always 

### PR DESCRIPTION
**Pull request by Razikus**
According to issue #83

### CODE REVIEW

**Comment by dfunckt** [comment]
Hey @Razikus it's not clear to me how this will help solve your use case. `restart: always` just means that Docker should restart a container if it exits, not run the container in the first place.

**Comment by Razikus** [comment]
> Hey @Razikus it's not clear to me how this will help solve your use case. `restart: always` just means that Docker should restart a container if it exits, not run the container in the first place/at startup.

Nope, it also start container at system startup, and on any failure
Check the docker documentation
https://docs.docker.com/config/containers/start-containers-automatically/

**Comment by dfunckt** [comment]
@Razikus I just tested this and it seems you're right.

I think however it's best to (1) only support a single entry point -- ie. the `scripts/compose` script -- and (2) not impose this behaviour on everyone. If you're still keen to have Docker start the containers at startup (and having the init system invoke it is not an option you like) you can still add the `restart` flag by extending the service definitions in your project's docker-compose file in `config/docker-compose.yml`.

**Comment by ab77** [comment]
@Razikus Hello, (and a very, very late thank you for you contribution), we've updated the build/deploy scaffold for openBalena today, including using a single Docker composition. We've set the default restart [unless-stopped](https://github.com/balena-io/open-balena/blob/master/docker-compose.yml#L67) on all containers (except for services which are responsible for e2e tests). Please feel free to reopen your PR, rebase on master and make any relevant contributions.

**Pull request closed without merging**
